[package]
name = "object-safe"
version = "0.1.0"
authors = ["Cerber Ursi <dev+rust@cerbe.ru>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }
quote = "1"
darling = "0.10"

[dev-dependencies]
trybuild = "1.0"
